/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Kushagra Srivastava",
  "tagline": "Developer & Researcher | Operating Systems & Compilers",
  "favicon": "img/favicon.ico",
  "url": "https://skushagra.com",
  "baseUrl": "/",
  "organizationName": "suobset",
  "projectName": "skushagra",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/suobset/skushagra/sidebars.js"
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Fineletters.",
          "blogListComponent": "@theme/BlogListPage",
          "blogDescription": "The Finechive Newsletter, by Kush S.",
          "postsPerPage": 5,
          "blogSidebarCount": 0
        },
        "theme": {
          "customCss": "/home/suobset/skushagra/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Kush S.",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "About Me"
        },
        {
          "to": "/docs/resume",
          "label": "Resume",
          "position": "left"
        },
        {
          "to": "/docs/ongoing",
          "label": "Ongoing",
          "position": "left"
        },
        {
          "href": "mailto:ksrivastava@umass.edu",
          "label": "Contact",
          "position": "left"
        },
        {
          "href": "https://www.flickr.com/photos/suobset/",
          "label": "Photography",
          "position": "right"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Official",
          "items": [
            {
              "label": "About Me",
              "to": "/docs/intro"
            },
            {
              "label": "Ongoing",
              "to": "/docs/ongoing"
            },
            {
              "label": "Work Experience",
              "to": "/docs/experience"
            },
            {
              "label": "Undergraduate",
              "to": "/docs/category/undergraduate"
            }
          ]
        },
        {
          "title": "Creative",
          "items": [
            {
              "label": "Hobby Projects",
              "to": "/docs/category/hobby"
            },
            {
              "label": "Photography & Digital Art",
              "to": "/docs/finechive/photography"
            },
            {
              "label": "Independent Code",
              "to": "/docs/category/independent-code--research"
            },
            {
              "label": "Don't Panic",
              "to": "/dontpanic"
            }
          ]
        },
        {
          "title": "On the Web",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/suobset/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/suobset"
            },
            {
              "html": "<a href=\"https://orcid.org/0000-0003-0656-5478\" style=\"color: #FFFFFF;\">\n\t\t\t\tKush S. ORCiD\n              \t<img alt=\"ORCID logo\" src=\"https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png\" width=\"16\" height=\"16\" />\n              \t</a>"
            },
            {
              "label": "Everything Else",
              "to": "/docs/links"
            }
          ]
        },
        {
          "title": "Site Meta",
          "items": [
            {
              "label": "Site Archive",
              "to": "/archive"
            },
            {
              "html": "<a href=\"source\"><img src=\"https://suobset.github.io/finechive-helper/88x31/gpl.gif\"></img></a>"
            },
            {
              "html": "<a href=\"https://skushagra.com/docs/finechive/scripting-shenanigans#delcookies\"><img src=\"https://suobset.github.io/finechive-helper/88x31/noocookie.gif\"></img></a>"
            },
            {
              "html": "<a href=\"bestViewedByAnyBrowser\"><img src=\"https://suobset.github.io/finechive-helper/88x31/lynx.gif\"></img></a>"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2017-2024 Kushagra Srivastava <br />\n        All views expressed here are my own, and not representative of my organization or university."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "prism": {
      "theme": {
        "plain": {
          "background": "#2a2139",
          "backgroundColor": "linear-gradient(to bottom, #2a2139 75%, #34294f)",
          "backgroundImage": "#34294f",
          "color": "#f92aad",
          "textShadow": "0 0 2px #100c0f, 0 0 5px #dc078e33, 0 0 10px #fff3"
        },
        "styles": [
          {
            "types": [
              "comment",
              "block-comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#495495",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#ccc"
            }
          },
          {
            "types": [
              "tag",
              "attr-name",
              "namespace",
              "number",
              "unit",
              "hexcode",
              "deleted"
            ],
            "style": {
              "color": "#e2777a"
            }
          },
          {
            "types": [
              "property",
              "selector"
            ],
            "style": {
              "color": "#72f1b8",
              "textShadow": "0 0 2px #100c0f, 0 0 10px #257c5575, 0 0 35px #21272475"
            }
          },
          {
            "types": [
              "function-name"
            ],
            "style": {
              "color": "#6196cc"
            }
          },
          {
            "types": [
              "boolean",
              "selector-id",
              "function"
            ],
            "style": {
              "color": "#fdfdfd",
              "textShadow": "0 0 2px #001716, 0 0 3px #03edf975, 0 0 5px #03edf975, 0 0 8px #03edf975"
            }
          },
          {
            "types": [
              "class-name",
              "maybe-class-name",
              "builtin"
            ],
            "style": {
              "color": "#fff5f6",
              "textShadow": "0 0 2px #000, 0 0 10px #fc1f2c75, 0 0 5px #fc1f2c75, 0 0 25px #fc1f2c75"
            }
          },
          {
            "types": [
              "constant",
              "symbol"
            ],
            "style": {
              "color": "#f92aad",
              "textShadow": "0 0 2px #100c0f, 0 0 5px #dc078e33, 0 0 10px #fff3"
            }
          },
          {
            "types": [
              "important",
              "atrule",
              "keyword",
              "selector-class"
            ],
            "style": {
              "color": "#f4eee4",
              "textShadow": "0 0 2px #393a33, 0 0 8px #f39f0575, 0 0 2px #f39f0575"
            }
          },
          {
            "types": [
              "string",
              "char",
              "attr-value",
              "regex",
              "variable"
            ],
            "style": {
              "color": "#f87c32"
            }
          },
          {
            "types": [
              "parameter"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "entity",
              "url"
            ],
            "style": {
              "color": "#67cdcc"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "ffffffee"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "entity"
            ],
            "style": {
              "cursor": "help"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "green"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
