/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Kushagra Srivastava",
  "tagline": "Operating Systems & Compilers Programmer | AI/ML Specialization",
  "favicon": "img/favicon.ico",
  "url": "https://skushagra.com",
  "baseUrl": "/",
  "organizationName": "suobset",
  "projectName": "skushagra",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/smith/Documents/skushagra/sidebars.js"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/Users/smith/Documents/skushagra/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Kush S.",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "About Me"
        },
        {
          "to": "/docs/category/the-finechive",
          "label": "Finechive",
          "position": "left"
        },
        {
          "to": "/docs/resume",
          "label": "Resume",
          "position": "left"
        },
        {
          "to": "/docs/category/research",
          "label": "Research",
          "position": "left"
        },
        {
          "href": "mailto:ksrivastava@umass.edu",
          "label": "Contact",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Site Highlights",
          "items": [
            {
              "label": "About Me + Everything",
              "to": "/docs/intro"
            },
            {
              "label": "Finechive",
              "to": "/docs/category/the-finechive"
            },
            {
              "label": "Research",
              "to": "/docs/category/research"
            }
          ]
        },
        {
          "title": "Code/Research",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/suobset/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/suobset"
            },
            {
              "html": "<a href=\"https://orcid.org/0000-0003-0656-5478\" style=\"color: #FFFFFF;\">\n\t\t\t\tKush S. ORCiD\n              \t<img alt=\"ORCID logo\" src=\"https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png\" width=\"16\" height=\"16\" />\n              \t</a>"
            }
          ]
        },
        {
          "title": "On the Web",
          "items": [
            {
              "label": "Threads",
              "href": "https://threads.net/@suobset"
            },
            {
              "label": "Everything Else",
              "to": "/docs/links"
            },
            {
              "label": "Don't Panic",
              "to": "/dontpanic"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2019-2024 Kushagra Srivastava"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#000000",
          "backgroundColor": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
